# Generated by cpp11: do not edit by hand

ts_reduce_ <- function(unit, value, when, local, custom, unit_names, grain, year_month, year_day, stats, sampling_step) {
  .Call(`_timesift_ts_reduce_`, unit, value, when, local, custom, unit_names, grain, year_month, year_day, stats, sampling_step)
}

ts_bin_starts_ <- function(local, grain, year_month, year_day) {
  .Call(`_timesift_ts_bin_starts_`, local, grain, year_month, year_day)
}

ts_bin_nexts_ <- function(bins, grain, year_month, year_day) {
  .Call(`_timesift_ts_bin_nexts_`, bins, grain, year_month, year_day)
}
