# Generated by cpp11: do not edit by hand

cg_reduce_ <- function(unit, value, when, local, custom, unit_names, window, year_month, year_day, stats, sampling_step) {
  .Call(`_climgrain_cg_reduce_`, unit, value, when, local, custom, unit_names, window, year_month, year_day, stats, sampling_step)
}

cg_bin_starts_ <- function(local, window, year_month, year_day) {
  .Call(`_climgrain_cg_bin_starts_`, local, window, year_month, year_day)
}

cg_bin_nexts_ <- function(bins, window, year_month, year_day) {
  .Call(`_climgrain_cg_bin_nexts_`, bins, window, year_month, year_day)
}
