# Generated by cpp11: do not edit by hand

tg_reduce_ <- function(unit, value, when, local, custom, unit_names, window, year_month, year_day, stats, sampling_step) {
  .Call(`_timegrain_tg_reduce_`, unit, value, when, local, custom, unit_names, window, year_month, year_day, stats, sampling_step)
}

tg_bin_starts_ <- function(local, window, year_month, year_day) {
  .Call(`_timegrain_tg_bin_starts_`, local, window, year_month, year_day)
}

tg_bin_nexts_ <- function(bins, window, year_month, year_day) {
  .Call(`_timegrain_tg_bin_nexts_`, bins, window, year_month, year_day)
}
